### ISSUE TITLE
Why the while?

### ISSUE THREAD

**Issue by marecotec** [Andranovich3/NRS-568--ArcGIS-Python-Course#1]
In the input challenge.. Some fakery going on there with the while loop to print ....

Otherwise, all looks very good. I'd like to see you use a few more comments though. just to give yourself some context.

**Comment by Andranovich3** [comment]
Ahhh, I put the while loop in there for cosmetics. Just wanted to build some suspense before it spit out the age. Should print three sets of periods and then finish.

Definitely will throw some more comments in, I forgot this time. Thanks for the feedback!

**Comment by marecotec** [comment]
Nothing wrong with it, definitely built up suspense! Good coding all round


Andrew J Davies,
University of Rhode Island,
Department of Biological Sciences

Room: CBLS 291
Email: davies@uri.edu
Personal: https://anddavies.co.uk
Group: https://marecotec.com
