### ISSUE TITLE
Mid-term

### ISSUE THREAD

**Issue by marecotec** [Andranovich3/NRS-568--ArcGIS-Python-Course#3]
**Cleanliness of code (10 points)**
Very clean and well lain out: 10/10

**Functionality (10 points)**
Some good function here, my only concern is the use of the hard code filenames that are very specific, i.e. WashingtonCountyCoastline.. could confuse a user who was running your routine on a different series of shapefile.

10/10

**Appropriate use of documentation (10 points)**
Exceptional, best I have seen for a while: 10/10

**Depth of processing operation (10 points)**
Not a fan of the question at the end, but it is a welcome demonstration of a different way of handlign the temp file clean up (when it works, see below). I would also not hard code your filter onto line 42, instead, allow people to change this as a variable earlier on.

10/10

**In addition, you must provide example data and minimize the amount of editing a user must make in order for the program to run (10 points).**

Ran into an issue with your files for the process being in subfolders, solved this by copying to my base directory.

Ran into another issue with your userInput questions, answer should be userInput.
![image](https://user-images.githubusercontent.com/1593936/77791456-08bad780-703d-11ea-8d9d-9f1769db9b8c.png)

![image](https://user-images.githubusercontent.com/1593936/77791494-196b4d80-703d-11ea-8018-9edf4b99803c.png)

9/10 extra mark available if you fix those minor issues

**Overall**
49/50

**Comment by Andranovich3** [comment]
Totally agree with the hardcoded file name and the "where clause". I guess I could just create a name based on the first few letters in the index maybe, and a variable for the clause? I always forget it's important to create files for multiple uses rather than a single go, as it'll save time in the long run!

I was wondering about the subfolders thing, makes sense. Should I just copy the files out of the "Coastline" and "Towns" folders and plop them right in next to the *.py file on GitHub?

And finally, no love for the user input?! I thought that was a fun little touch, haha. Completely missed error in the elif statement, changing now.

Appreciate all the feedback!

**Comment by marecotec** [comment]
> Totally agree with the hardcoded file name and the "where clause". I guess I could just create a name based on the first few letters in the index maybe, and a variable for the clause? I always forget it's important to create files for multiple uses rather than a single go, as it'll save time in the long run!
> 
I tend to use species names, but the problem is that you may not end up with a unique file name at the end. Depends on your use case to be honest.
> I was wondering about the subfolders thing, makes sense. Should I just copy the files out of the "Coastline" and "Towns" folders and plop them right in next to the *.py file on GitHub?
> 
I would normally just call a subfolder with the name “Data”, and in there keep all my files. The python file would be in the root, i.e.

Python File
Data/Coasts.shp
Data/Towns.shp

etc
> And finally, no love for the user input?! I thought that was a fun little touch, haha. Completely missed error in the elif statement, changing now.
> 
> 
Its a nice demo, pain is that once we move to a toolbox, we wont be able to use that functionality through ArcMap.

> Appreciate all the feedback!
> 

No worries!
